name: CI

on: [push, pull_request]

jobs:
  rb1_xbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build ARK
        run: |
          rb1/dependencies/python/configure_build.py xbox
          rb1/dependencies/linux/ninja
      - name: Remove .gitkeep
        run: |
          find . -name ".gitkeep" -type f -delete
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: RB1-Patch-Xbox
          path: rb1/out/xbox

  rb1_ps3:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/command-output-file-action@v1.1
        with:
          command_line: echo InstallDirectory = BLUS30050
          output_file_name: rb1/ps3_package.conf
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build ARK
        run: |
          python rb1/dependencies/python/configure_build.py ps3
          rb1/dependencies/windows/ninja.exe
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP1018-BLUS30050_00-RB1PATCHH"
          $packageversion="1.07"
          rb1/dependencies/windows/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) rb1/ps3_package.conf out/ps3
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: RB1-Patch-PS3
          path: '*.pkg'

  lrb_xbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build ARK
        run: |
          lrb/dependencies/python/configure_build.py xbox
          lrb/dependencies/linux/ninja
      - name: Remove .gitkeep
        run: |
          find . -name ".gitkeep" -type f -delete
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: LRB-Patch-Xbox
          path: lrb/_build/xbox

  lrb_ps3:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/command-output-file-action@v1.1
        with:
          command_line: echo InstallDirectory = BLUS30050
          output_file_name: lrb/ps3_package.conf
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build ARK
        run: |
          python lrb/dependencies/python/configure_build.py ps3
          lrb/dependencies/windows/ninja.exe
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP1018-BLUS30382_00-LRBPATCHH"
          $packageversion="1.01"
          lrb/dependencies/windows/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) lrb/ps3_package.conf out/ps3
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: LRB-Patch-PS3
          path: '*.pkg'

  tbrb_xbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build ARK
        run: |
          tbrb/dependencies/python/configure_build.py xbox
          tbrb/dependencies/linux/ninja
      - name: Remove .gitkeep
        run: |
          find . -name ".gitkeep" -type f -delete
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: TBRB-Patch-Xbox
          path: tbrb/_build/xbox

  tbrb_ps3:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/command-output-file-action@v1.1
        with:
          command_line: echo InstallDirectory = BLUS30050
          output_file_name: tbrb/ps3_package.conf
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build ARK
        run: |
          python tbrb/dependencies/python/configure_build.py ps3
          tbrb/dependencies/windows/ninja.exe
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP0006-BLUS30282_00-TBRBPATCH"
          $packageversion="1.00"
          tbrb/dependencies/windows/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) tbrb/ps3_package.conf out/ps3
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: TBRB-Patch-PS3
          path: '*.pkg'

  gdrb_xbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build ARK
        run: |
          gdrb/dependencies/python/configure_build.py xbox
          gdrb/dependencies/linux/ninja
      - name: Remove .gitkeep
        run: |
          find . -name ".gitkeep" -type f -delete
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GDRB-Patch-Xbox
          path: gdrb/_build/xbox

  gdrb_ps3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build ARK
        run: |
          gdrb/dependencies/python/configure_build.py ps3
          gdrb/dependencies/linux/ninja
      - name: Remove .gitkeep
        run: |
          find . -name ".gitkeep" -type f -delete
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GDRB-Patch-PS3
          path: gdrb/_build/ps3